base:
  verbose: 1
  save_path: "."
  seed: 42069
  device: "cuda:0"

dataset:
  loc: "./example_images"

dataloader:
  params:
    batch_size: 1

model:
  config: "./FIQA/configs/model_config.yaml"
  weight: "./FIQA/weights/aikd-best.pth"

